###
post http://localhost:3000/api/students/register
Content-Type: application/json

{
  "studentName": "M Nikhila",
  "studentEmail": "n211092@rguktn.ac.in",
  "studentId": "N211092",
  "studentRollNumber": "60",
  "externalSetNumber": 1,
  "internalSetNumber": 3,
  "vivaSetNumbersArray": [2, 4, 6, 6,7,8,9,5,8,10],
  "className":"cse-5"
}

###
post https://dbms-backend-g8wg.onrender.com/api/students/login
Content-Type: application/json

{
  "studentId": "N210522",
  "studentEmail": "n210522@rguktn.ac.in",
  "studentRollNumber": "33"
}


###
post https://dbms-backend-g8wg.onrender.com/api/students/login
Content-Type: application/json

###
GET http://localhost:3000/api/students/response/N210972
Content-Type: application/json


### its ok all right
