###
post http://localhost:3000/api/students/register
Content-Type: application/json

{
  "studentName": "Sribabu ",
  "studentEmail": "n210522@rguktn.ac.in",
  "studentId": "N210522",
  "studentRollNumber": "33",
  "externalSetNumber": 5,
  "internalSetNumber": 3,
  "vivaSetNumbersArray": [2, 4, 6, 8]
}

###
post https://dbms-backend-g8wg.onrender.com/api/students/login
Content-Type: application/json

{
  "studentId": "N210522",
  "studentEmail": "n210522@rguktn.ac.in",
  "studentRollNumber": "33"
}


### its ok all right
