###
post http://localhost:3000/api/students/register
Content-Type: application/json

{
  "studentName": "Sribabu s",
  "studentEmail": "n2ss10ddss501@rguktn.ac.in",
  "studentId": "N21dd0ssss501",
  "studentRollNumber": "1",
  "externalSetNumber": 5,
  "internalSetNumber": 3,
  "vivaSetNumbersArray": [2, 4, 6, 6,7,8,9,5,8,10],
  "className":"cse-6"
}

###
post https://dbms-backend-g8wg.onrender.com/api/students/login
Content-Type: application/json

{
  "studentId": "N210522",
  "studentEmail": "n210522@rguktn.ac.in",
  "studentRollNumber": "33"
}


###
post https://dbms-backend-g8wg.onrender.com/api/students/login
Content-Type: application/json

###
GET http://localhost:3000/api/students/response/N210972
Content-Type: application/json


### its ok all right
